# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('isbn', models.IntegerField()),
                ('name', models.CharField(max_length=256, null=True)),
                ('book_type', models.CharField(choices=[(b'Paper-Back', b'PAPER_BACK'), (b'Hard Cover', b'HARD_BIND'), (b'Online', b'ONLINE')], max_length=64)),
                ('metadata_ref', models.TextField(blank=True, null=True)),
                ('publication', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='grpc_book_service.Author')),
            ],
        ),
    ]
