# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (
    lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='app.proto',
    package='grpc_protos',
    syntax='proto3',
    serialized_pb=_b(
        '\n\tapp.proto\x12\x0bgrpc_protos\"*\n\x0bPublication\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x87\x02\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x31\n\tbook_type\x18\x05 \x01(\x0e\x32\x1e.grpc_protos.Book.BookTypeEnum\x12\x11\n\x05\x63odes\x18\x06 \x03(\x01\x42\x02\x10\x01\x12\x14\n\x0cmetadata_ref\x18\x07 \x01(\t\x12-\n\x0bpublication\x18\x08 \x01(\x0b\x32\x18.grpc_protos.Publication\"9\n\x0c\x42ookTypeEnum\x12\x0e\n\nPAPER_BACK\x10\x00\x12\r\n\tHARD_BIND\x10\x01\x12\n\n\x06ONLINE\x10\x02\"*\n\x11QueryBooksRequest\x12\x15\n\rauthor_prefix\x18\x01 \x01(\x03\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\x03\x32\x9b\x01\n\x0fGRPCBookService\x12G\n\x0eQueryBooksPost\x12\x1e.grpc_protos.QueryBooksRequest\x1a\x11.grpc_protos.Book\"\x00\x30\x01\x12?\n\x0bGetBookPost\x12\x1b.grpc_protos.GetBookRequest\x1a\x11.grpc_protos.Book\"\x00\x62\x06proto3')
)

_BOOK_BOOKTYPEENUM = _descriptor.EnumDescriptor(
    name='BookTypeEnum',
    full_name='grpc_protos.Book.BookTypeEnum',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='PAPER_BACK', index=0, number=0,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='HARD_BIND', index=1, number=1,
            options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='ONLINE', index=2, number=2,
            options=None,
            type=None),
    ],
    containing_type=None,
    options=None,
    serialized_start=277,
    serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_BOOK_BOOKTYPEENUM)

_PUBLICATION = _descriptor.Descriptor(
    name='Publication',
    full_name='grpc_protos.Publication',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='grpc_protos.Publication.name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='email', full_name='grpc_protos.Publication.email', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=26,
    serialized_end=68,
)

_BOOK = _descriptor.Descriptor(
    name='Book',
    full_name='grpc_protos.Book',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='isbn', full_name='grpc_protos.Book.isbn', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='name', full_name='grpc_protos.Book.name', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='author', full_name='grpc_protos.Book.author', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='title', full_name='grpc_protos.Book.title', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='book_type', full_name='grpc_protos.Book.book_type', index=4,
            number=5, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='codes', full_name='grpc_protos.Book.codes', index=5,
            number=6, type=1, cpp_type=5, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(),
                                              _b('\020\001')),
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='metadata_ref', full_name='grpc_protos.Book.metadata_ref',
            index=6,
            number=7, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='publication', full_name='grpc_protos.Book.publication',
            index=7,
            number=8, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _BOOK_BOOKTYPEENUM,
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=71,
    serialized_end=334,
)

_QUERYBOOKSREQUEST = _descriptor.Descriptor(
    name='QueryBooksRequest',
    full_name='grpc_protos.QueryBooksRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='author_prefix',
            full_name='grpc_protos.QueryBooksRequest.author_prefix', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=336,
    serialized_end=378,
)

_GETBOOKREQUEST = _descriptor.Descriptor(
    name='GetBookRequest',
    full_name='grpc_protos.GetBookRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='isbn', full_name='grpc_protos.GetBookRequest.isbn', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=380,
    serialized_end=410,
)

_BOOK.fields_by_name['book_type'].enum_type = _BOOK_BOOKTYPEENUM
_BOOK.fields_by_name['publication'].message_type = _PUBLICATION
_BOOK_BOOKTYPEENUM.containing_type = _BOOK
DESCRIPTOR.message_types_by_name['Publication'] = _PUBLICATION
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['QueryBooksRequest'] = _QUERYBOOKSREQUEST
DESCRIPTOR.message_types_by_name['GetBookRequest'] = _GETBOOKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Publication = _reflection.GeneratedProtocolMessageType('Publication',
                                                       (_message.Message,),
                                                       dict(
                                                           DESCRIPTOR=_PUBLICATION,
                                                           __module__='app_pb2'
                                                           # @@protoc_insertion_point(class_scope:grpc_protos.Publication)
                                                       ))
_sym_db.RegisterMessage(Publication)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,),
                                                dict(
                                                    DESCRIPTOR=_BOOK,
                                                    __module__='app_pb2'
                                                    # @@protoc_insertion_point(class_scope:grpc_protos.Book)
                                                ))
_sym_db.RegisterMessage(Book)

QueryBooksRequest = _reflection.GeneratedProtocolMessageType(
    'QueryBooksRequest', (_message.Message,), dict(
        DESCRIPTOR=_QUERYBOOKSREQUEST,
        __module__='app_pb2'
        # @@protoc_insertion_point(class_scope:grpc_protos.QueryBooksRequest)
    ))
_sym_db.RegisterMessage(QueryBooksRequest)

GetBookRequest = _reflection.GeneratedProtocolMessageType('GetBookRequest',
                                                          (_message.Message,),
                                                          dict(
                                                              DESCRIPTOR=_GETBOOKREQUEST,
                                                              __module__='app_pb2'
                                                              # @@protoc_insertion_point(class_scope:grpc_protos.GetBookRequest)
                                                          ))
_sym_db.RegisterMessage(GetBookRequest)

_BOOK.fields_by_name['codes'].has_options = True
_BOOK.fields_by_name['codes']._options = _descriptor._ParseOptions(
    descriptor_pb2.FieldOptions(), _b('\020\001'))

_GRPCBOOKSERVICE = _descriptor.ServiceDescriptor(
    name='GRPCBookService',
    full_name='grpc_protos.GRPCBookService',
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=413,
    serialized_end=568,
    methods=[
        _descriptor.MethodDescriptor(
            name='QueryBooksPost',
            full_name='grpc_protos.GRPCBookService.QueryBooksPost',
            index=0,
            containing_service=None,
            input_type=_QUERYBOOKSREQUEST,
            output_type=_BOOK,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name='GetBookPost',
            full_name='grpc_protos.GRPCBookService.GetBookPost',
            index=1,
            containing_service=None,
            input_type=_GETBOOKREQUEST,
            output_type=_BOOK,
            options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_GRPCBOOKSERVICE)

DESCRIPTOR.services_by_name['GRPCBookService'] = _GRPCBOOKSERVICE

# @@protoc_insertion_point(module_scope)
